import { db } from "./index";
import { products } from "./schema";

const productImages = [
  "https://images.pexels.com/photos/18584221/pexels-photo-18584221.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/28701950/pexels-photo-28701950.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/19887010/pexels-photo-19887010.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/16272623/pexels-photo-16272623.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/28701960/pexels-photo-28701960.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/19887012/pexels-photo-19887012.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/30257616/pexels-photo-30257616.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/18956666/pexels-photo-18956666.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/19862949/pexels-photo-19862949.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/32037694/pexels-photo-32037694.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/34582210/pexels-photo-34582210.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/33055601/pexels-photo-33055601.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
];

const seedProducts = [
  {
    name: "SHADOW OVERSIZED TEE",
    slug: "shadow-oversized-tee",
    description: "Premium 300gsm heavyweight cotton oversized tee. Drop shoulder design with raw-cut hem. Garment dyed for a washed-out underground aesthetic. Made in Australia.",
    price: 89.00,
    comparePrice: 120.00,
    category: "Oversized Tees",
    images: [productImages[0], productImages[1], productImages[6]],
    colors: [{ name: "Washed Black", hex: "#1a1a1a" }, { name: "Stone", hex: "#b5a99a" }, { name: "Off White", hex: "#f5f0eb" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    isLimitedDrop: true,
    dropEndsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    inStock: true,
    stockCount: 47,
    featured: true,
  },
  {
    name: "NOCTURNAL HOODIE",
    slug: "nocturnal-hoodie",
    description: "480gsm heavyweight French terry hoodie. Boxy fit with kangaroo pocket and premium YKK hardware. Embossed logo detail. Limited to 200 units worldwide.",
    price: 189.00,
    comparePrice: 250.00,
    category: "Hoodies",
    images: [productImages[2], productImages[3], productImages[4]],
    colors: [{ name: "Midnight", hex: "#0d0d0d" }, { name: "Concrete", hex: "#808080" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    isLimitedDrop: true,
    dropEndsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    inStock: true,
    stockCount: 23,
    featured: true,
  },
  {
    name: "UNDERGROUND CARGO",
    slug: "underground-cargo",
    description: "Ripstop nylon cargo pants with multiple utility pockets. Adjustable cuffs with snap buttons. Water-resistant coating. Relaxed fit through thigh with tapered leg.",
    price: 159.00,
    category: "Cargo Pants",
    images: [productImages[4], productImages[5], productImages[0]],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Olive", hex: "#556B2F" }, { name: "Sand", hex: "#C2B280" }],
    sizes: ["28", "30", "32", "34", "36"],
    isLimitedDrop: false,
    inStock: true,
    stockCount: 85,
    featured: true,
  },
  {
    name: "PHANTOM JACKET",
    slug: "phantom-jacket",
    description: "Technical shell jacket with reflective detailing. Storm flap construction with sealed seams. Packable design with integrated hood. Premium DWR coating.",
    price: 299.00,
    comparePrice: 380.00,
    category: "Jackets",
    images: [productImages[6], productImages[7], productImages[1]],
    colors: [{ name: "Stealth Black", hex: "#111111" }, { name: "Graphite", hex: "#383838" }],
    sizes: ["S", "M", "L", "XL"],
    isLimitedDrop: true,
    dropEndsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    inStock: true,
    stockCount: 15,
    featured: true,
  },
  {
    name: "VOID OVERSIZED TEE",
    slug: "void-oversized-tee",
    description: "Ultra heavyweight 350gsm oversized tee with back print. Screen printed graphic with puff print details. Double stitched for durability.",
    price: 99.00,
    category: "Oversized Tees",
    images: [productImages[8], productImages[9], productImages[2]],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Charcoal", hex: "#36454F" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    isLimitedDrop: false,
    inStock: true,
    stockCount: 120,
    featured: false,
  },
  {
    name: "DUSK ZIP-UP",
    slug: "dusk-zip-up",
    description: "500gsm premium zip-up hoodie with metal hardware. Split kangaroo pockets. Ribbed cuffs and hem. Oversized fit with dropped shoulders.",
    price: 219.00,
    category: "Hoodies",
    images: [productImages[10], productImages[11], productImages[3]],
    colors: [{ name: "Washed Black", hex: "#1a1a1a" }, { name: "Cement", hex: "#ABABAB" }],
    sizes: ["S", "M", "L", "XL"],
    isLimitedDrop: false,
    inStock: true,
    stockCount: 65,
    featured: true,
  },
  {
    name: "CHROME CHAIN",
    slug: "chrome-chain",
    description: "Stainless steel Cuban link chain with custom clasp. 60cm length. Chrome finish. Comes in premium gift box.",
    price: 79.00,
    category: "Accessories",
    images: [productImages[5], productImages[3], productImages[11]],
    colors: [{ name: "Chrome", hex: "#C0C0C0" }],
    sizes: ["60cm"],
    isLimitedDrop: false,
    inStock: true,
    stockCount: 200,
    featured: false,
  },
  {
    name: "ECLIPSE CARGO SHORTS",
    slug: "eclipse-cargo-shorts",
    description: "Premium twill cargo shorts with utility pockets. Relaxed fit with elastic waistband and drawstring. Enzyme washed for a broken-in feel.",
    price: 119.00,
    category: "Cargo Pants",
    images: [productImages[9], productImages[0], productImages[6]],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Khaki", hex: "#BDB76B" }],
    sizes: ["28", "30", "32", "34", "36"],
    isLimitedDrop: false,
    inStock: true,
    stockCount: 90,
    featured: false,
  },
  {
    name: "TRAPSTAR OVERSIZED TEE",
    slug: "trapstar-oversized-tee",
    description: "Limited collaboration oversized tee. 320gsm organic cotton. Exclusive embroidered patch detail. Only 100 units made.",
    price: 129.00,
    comparePrice: 180.00,
    category: "Oversized Tees",
    images: [productImages[1], productImages[10], productImages[8]],
    colors: [{ name: "Vintage Black", hex: "#1c1c1c" }],
    sizes: ["M", "L", "XL"],
    isLimitedDrop: true,
    dropEndsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    inStock: true,
    stockCount: 8,
    featured: true,
  },
  {
    name: "MONOCHROME BEANIE",
    slug: "monochrome-beanie",
    description: "Ribbed knit beanie in premium merino wool blend. Embroidered logo. One size fits all.",
    price: 49.00,
    category: "Accessories",
    images: [productImages[7], productImages[2], productImages[5]],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Grey", hex: "#808080" }],
    sizes: ["One Size"],
    isLimitedDrop: false,
    inStock: true,
    stockCount: 150,
    featured: false,
  },
  {
    name: "STEALTH BOMBER",
    slug: "stealth-bomber",
    description: "MA-1 inspired bomber jacket in premium nylon. Padded construction with satin lining. Custom metal zippers and ribbed trim.",
    price: 349.00,
    category: "Jackets",
    images: [productImages[11], productImages[4], productImages[7]],
    colors: [{ name: "Jet Black", hex: "#0a0a0a" }, { name: "Army", hex: "#4B5320" }],
    sizes: ["S", "M", "L", "XL"],
    isLimitedDrop: true,
    dropEndsAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    inStock: true,
    stockCount: 30,
    featured: true,
  },
  {
    name: "GRIP SOCKS",
    slug: "grip-socks",
    description: "Premium crew socks in organic cotton. Cushioned sole with arch support. Logo knit detail.",
    price: 29.00,
    category: "Accessories",
    images: [productImages[3], productImages[6], productImages[9]],
    colors: [{ name: "Black", hex: "#000000" }, { name: "White", hex: "#FFFFFF" }],
    sizes: ["S/M", "L/XL"],
    isLimitedDrop: false,
    inStock: true,
    stockCount: 300,
    featured: false,
  },
];

async function seed() {
  console.log("Seeding products...");
  for (const product of seedProducts) {
    await db.insert(products).values(product).onConflictDoNothing();
  }
  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
